
export const Constant = {
    reg : /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    tital:"Please enter your information:",
    firstnamePlaceholder: "First name",
    lastnamePlaceholder: "Last name",
    streetAddressPlaceholder: "Street Address",
    cityPlaceholder: "City",
    statePlaceholder: "State",
    zipPlaceholder: "Zip",
    emailPlaceholder: "Email",
    createPasswordPlaceholder: "Create Password",
    confirmPasswordPlaceholder: "Connfirm Password",
    submit: "Submit",
    reset: "Reset",
    
    messageFirstname: "Please enter first name.",
    messageLastName: "Please enter last name.",
    messageStreetAddress: "Please enter street address.",
    messageCity: "Please enter city.",
    messageState: "Please enter state.",
    messageZipcode: "Please enter zipcode.",
    messageEmailAddress: "Please enter email address.",
    messageValidEmailAddress: "Please enter valid email address.",
    messageCreatePassword: "Please enter create password.",
    messageConfirmPassword: "Please enter confirm password.",
    messageNotMatchPassword: "Create password does not match with confirm passord.",
};
